const USER_ACTION = {
	USERS_FETCH: 'USERS_FETCH',
	USERS_FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
	USERS_FETCH_FAILED: 'USERS_FETCH_FAILED',

	USER_DELETE: 'USER_DELETE',
	USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
	USER_DELETE_FAILED: 'USER_DELETE_FAILED',

	USER_ADD: 'USER_ADD',
	USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
	USER_ADD_FAILED: 'USER_ADD_FAILED',

	USER_UPDATE: 'USER_UPDATE',
	USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
	USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
}

const TASK_ACTION = {
	TASKS_FETCH: 'TASKS_FETCH',
	TASKS_FETCH_SUCCESS: 'TASKS_FETCH_SUCCESS',
	TASKS_FETCH_FAILED: 'TASKS_FETCH_FAILED',

	TASK_DELETE: 'TASK_DELETE',
	TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
	TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',

	TASK_ADD: 'TASK_ADD',
	TASK_ADD_SUCCESS: 'TASK_ADD_SUCCESS',
	TASK_ADD_FAILED: 'TASK_ADD_FAILED',

	TASK_UPDATE: 'TASK_UPDATE',
	TASK_UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
	TASK_UPDATE_FAILED: 'TASK_UPDATE_FAILED',
}

const BASE_ACTION = {
	BASE_API_START: 'BASE_API_START',
	BASE_API_SUCCESS: 'BASE_API_SUCCESS',
	BASE_API_FAILED: 'BASE_API_FAILED',
}

const AUTH_ACTION = {
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
	AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',


	AUTH_LOGOUT: 'AUTH_LOGOUT',
	AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
	AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',

	AUTH_SIGN_UP: 'AUTH_SIGN_UP',
	AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
	AUTH_SIGN_UP_FAILED: 'AUTH_SIGN_UP_FAILED',
}


export const ACTIONS = { ...USER_ACTION, ...TASK_ACTION, ...BASE_ACTION, ...AUTH_ACTION };


